multishop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _



urlpatterns = [
    path(r'^currencies/', include('currencies.urls')),
    path(_('admin/'), admin.site.urls),
    #  path('', include('store.urls')),
]

urlpatterns += i18n_patterns(
    path('i18n', include('django.conf.urls.i18n')),
    path('', include('store.urls', namespace='store')),
   # path('selectcurrency/', selectcurrency, name='selectcurrency'),
   # path('savelangcurr/', savelangcurr, name='savelangcurr'),
    prefix_default_language=False
)
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *

app_name = 'store'

urlpatterns = [
    # path('', ProductListView.as_view, name='product_list'),
    path('', product_list, name='product_list'),
    path('category/<int:category_id>/', category_products, name='category'),
    #  path('product/<slug:slug>/', product_detail, name='product_detail'),
    path('category/<slug:slug>/', category_page, name='category_detail'),
    path('product/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    # path('request/', RequestInfoView.as_view(), name='request'),
    path('cart/', cart, name='cart'),
    path('to_cart/<int:product_id>/<str:action>/', to_cart, name='to_cart'),
    path('clear_cart/', clear_cart, name='clear_cart'),
    path('checkout/', checkout, name='checkout'),
    path('shop/', shop, name='shop'),
    path('payment/', create_checkout_sessions, name='payment'),
    path('payment_success/', successPayment, name='success'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('contact/', contact, name='contact'),
    path('shop_detail/', shop_detail, name='shop_detail'),
    path('about/', about, name='about'),
    path('FAQ/', FAQs, name='FAQs'),
    path('profile/', profile, name='users-profile'),
    path('selectcurrency/', selectcurrency, name='selectcurrency'),
    path('savelangcurr/', savelangcurr, name='savelangcurr'),
]

store/forms.py
from django import forms
import datetime
import re
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.translation import gettext_lazy as _
from django.utils.translation import activate, get_language


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control',
                                                 'placeholder': 'Firstname...'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control',
                                                'placeholder': 'Lastname...'})
        }


class ShippingForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = ['address', 'city', 'state', 'shipping_zip', 'phone']
        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control',
                                              'placeholder': 'Address...'}),
            'city': forms.Select(attrs={'class': 'form-select',
                                        'placeholder': 'City...'}),
            'state': forms.TextInput(attrs={'class': 'form-control',
                                            'placeholder': 'State...'}),
            'shipping_zip': forms.TextInput(attrs={'class': 'form-control',
                                                   'placeholder': 'Shipping Zip...'}),
            'phone': forms.TextInput(attrs={'class': 'form-control',
                                            'placeholder': 'Phone...'})
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Username:', max_length=16, help_text="Max 16 symbols",
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Username'
                               }))
    password = forms.CharField(label='Password:', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Your Password'
    }))


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your Password'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Submit Password'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username'
    }))
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Your name'
        }))
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Your surname'
        }))
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Your email address'
        }))
    birthday = forms.DateTimeField(widget=forms.DateTimeInput(attrs={
        'class': 'form-control',
        'placeholder': 'Birthday'
    }))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'birthday', 'password1', 'password2')

    check = forms.BooleanField(required=True)


def cc_expire_years():
    current_year = datetime.datetime.now().year
    years = range(current_year, current_year + 12)
    return [(str(x), str(x)) for x in years]


def cc_expire_months():
    months = []
    for month in range(1, 13):
        if len(str(month)) == 1:
            numeric = '0' + str(month)
        else:
            numeric = str(month)

        months.append((numeric, datetime.date(2021, 3, 2).strftime('%B')))

    return months


CARD_TYPES = (('Mastercard', 'Mastercard'),
              ('VISA', 'VISA'),
              ('AMEX', 'AMEX'),
              ('Discover', 'Discover'),)


def strip_non_numbers(data):
    """ gets rid of all non-number characters """
    non_numbers = re.compile('\D')
    return non_numbers.sub('', data)


# Gateway test credit cards won't pass this validation
def cardLuhnChecksumIsValid(card_number):
    """ checks to make sure that the card passes a luhn mod-10 checksum """
    sum = 0
    num_digits = len(card_number)
    oddeven = num_digits & 1
    for count in range(0, num_digits):
        digit = int(card_number[count])
        if not ((count & 1) ^ oddeven):
            digit = digit * 2
        if digit > 9:
            digit = digit - 9
        sum = sum + digit
    return ((sum % 10) == 0)

store/views.py
from django.core.checks import messages
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.utils import translation

from .models import *
from django.views.generic import DetailView, ListView, CreateView
from random import randint
from .forms import CustomerForm, ShippingForm
from .utils import *

import stripe
from django.contrib import messages
from .forms import RegisterForm, LoginForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _
from django.utils.translation import activate, get_language, gettext
from multishop import settings


# Create your views here.
# class ProductListView(ListView):
#  model = Product
#  context_object_name = 'categories'

# extra_context = {
#     'title': 'MULTI SHOP - ONLINE',

#  }
# template_name = 'store/product_list.html'

#  def get_queryset(self):
#    categories = Category.objects.filter(parent=None)
#   return categories


def profile(request):
    return render(request, 'users/profile.html')


def product_list(request):
    if not request.session.has_key('currency'):
        request.session['currency'] = settings.DEFAULT_CURRENCY

    #  setting = Setting.objects.get(pk=1)
    products = Product.objects.all().order_by('-id')[:4]
    defaultlang = settings.LANGUAGE_CODE[0:2]
    currentlang = request.LANGUAGE_CODE[0:2]

    if defaultlang != currentlang:
        setting = settings.LANGUAGES.objects.get(language=currentlang)
        products = Product.objects.row(
            'SELECT p.id, p.price, l.title, l.description, l.slang'
            'FROM product as p'
            'LEFT JOIN productlang as l '
            'ON p.id = l.product_id'
            'WHERE l.language ORDER_BY p.id DESC LIMIT 4', [currentlang]
        )

    products_slider = Product.objects.all().order_by('id')[:4]
    products_picked = Product.objects.all().order_by('?')[:4]
    categories = Category.objects.filter(parent=None)
    trans = translate(language='ru')
    context = {
        'title': 'MULTI SHOP - ONLINE',
        'setting': 'setting',
        'categories': categories,
        'products': products,
        'products_slider': products_slider,
        'products_picked': products_picked,
        'trans': trans,

    }
    return render(request, 'store/product_list.html', context)


def translate(language):
    cur_language = get_language()
    try:
        activate(language)
        text = gettext('Shopping')
    finally:
        activate(cur_language)
    return text


def category_products(request, category_id, category_slug):
    products = Product.objects.filter(category_id=category_id)
    products = products.order_by('-created_at')

    category = Category.objects.get(pk=category_id, slug=category_slug)
    categories = Category.objects.all()
    if category_slug:
        category_slug = get_object_or_404(Category, slug=category_slug)
    context = {
        'title': f'Category: {category.title}',
        'categories': categories,
        'products': products,
        'category': category_slug
    }

    return render(request, 'components/_nav.html', context)


# def product_detail(request, slug):
#  product = get_object_or_404(Product, slug=slug, quantity=True)
# product = Product.objects.get(slug=slug)
# context = {
#     'product': product
# }
# return render(request, 'store/components/product_detail.html', context)
# class RequestInfoView(CreateView):
#  template_name = 'request_info.html'
# form_class = RequestInfoForm
# success_url = '/thanks/'

#  def form_valid(self, form):
#     name = form.cleaned_data['name']
#    email = form.cleaned_data['email']
#   phone = form.cleaned_data['phone']
#  state = form.cleaned_data['state']
# vendor = form.cleaned_data['vendor']
# product_name = form.cleaned_data['product']

# message = name + " " + email + " " + state + " " + str(product_name)

#  html_message = render_to_string('mail_request.html', context=({'name': name,
#                                                                'email': email,
#                                                              'phone': phone,
#                                                             'state': state,
#                                                              'product': product_name}))
# try:
#    send_mail('Sales Inquiry from: ' + name, message, email, ['test@example.com'],
#             html_message=html_message)
# except:
#   return HttpResponse('Invalid header found.')
# return super().form_valid(form)


class ProductDetail(DetailView):
    model = Product
    template_name = 'store/components/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        product = Product.objects.get(slug=self.kwargs['slug'])
        context['title'] = f'Product: {product.title}'

        products = Product.objects.all()
        data = []
        for i in range(0):
            random_index = randint(0, len(products))
            p = products[random_index]

            if p not in data:
                data.append(p)

        context['products'] = data

        return context


# class CategoryView(ListView):
#    model = Product
#    context_object_name = 'products'
#  template_name = 'store/_category_page.html'

#   def get_queryset(self):
#      main_category = Category.objects.get(slug=self.kwargs['slug'])
#     subcategories = main_category.subcategories.all()
#    data = []
#     for subcategory in subcategories:
#        products = subcategory.products.all()
#        for product in products:
#            data.append(product)
#           return data


def category_page(request, slug):
    main_category = Category.objects.get(category=request.POST.get('category'), slug=slug)
    subcategories = main_category.subcategories.all()
    products = Product.objects.filter(category__in=subcategories)
    paginate_by = 4

    context = {
        'products': products,
        'main_category': main_category,
        'subcategories': subcategories,
        'pagination': paginate_by
    }

    sort_fields = request.Get.get('sort')
    if sort_fields:
        context['products'] = context['products'].order_by(*sort_fields)

    return render(request, 'store/category_page.html', context)


def cart(request):
    cart_info = get_cart_data(request)

    context = {
        'cart_total_quantity': cart_info['cart_total_quantity'],
        'order': cart_info['order'],
        'products': cart_info['products']
    }
    return render(request, 'store/cart.html', context)


def to_cart(request, product_id, action):
    if request.user.is_authenticated:
        user_cart = CartForAuthenticatedUser(request, product_id, action)
        return redirect('cart', {'user_cart': user_cart})
    else:
        messages.error(request, "Xaridni amalga oshirish uchun, Avrotizatsiyadan yoki ro'yxatdan o'ting")
        return redirect('login_registration')


def checkout(request):
    cart_info = get_cart_data(request)
    context = {
        'cart_total_quantity': cart_info['cart_total_quantity'],
        'order': cart_info['order'],
        'items': cart_info['products'],
        'customer_form': CustomerForm(),
        'shipping_form': ShippingForm(),
        'title': 'Make an order'
    }
    return render(request, 'store/checkout.html', context)


def shop(request):
    return render(request, 'store/shop.html', {})


def create_checkout_sessions(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    if request.method == 'POST':
        '''Bu yerda foydalanuvchi ma'lumotlarini saqlaymiz.'''
        user_cart = CartForAuthenticatedUser(request)
        cart_info = user_cart.get_cart_info()
        customer_form = CustomerForm(data=request.POST)
        if customer_form.is_valid():
            customer = Customer.objects.get(user=request.user)
            customer.first_name = customer_form.cleaned_data['first_name']
            customer.last_name = customer_form.cleaned_data['last_name']
            customer.save()
            user = User.objects.get(username=request.user.username)
            user.first_name = customer_form.cleaned_data['first_name']
            user.last_name = customer_form.cleaned_data['last_name']
            user.save()
        shipping_form = ShippingForm(data=request.POST)
        if shipping_form.is_valid():
            address = shipping_form.save(commit=False)
            address.customer = Customer.objects.get(user=request.user)
            address.order = user_cart.get_cart_info()['order']
            address.save()

        total_price = cart_info['cart_total_price']
        total_quantity = cart_info['cart_total_quantity']
        session = stripe.checkout.Session.create(
            line_items=[{
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': 'Products'
                    },
                    'unit_amount': int(total_price * 100)
                },
                'quantity': total_quantity
            }],
            mode='payment',
            success_url=request.build_absolute_uri(reverse('success')),
            cancel_url=request.build_absolute_uri(reverse('success')),
        )
        return redirect(session.url, 303)


def successPayment(request):
    user_cart = CartForAuthenticatedUser(request)
    user_cart.clear()
    messages.success(request, "The Payment was made successfully!")
    return render(request, 'store/success.html')


def clear_cart(request):
    user_cart = CartForAuthenticatedUser(request)
    order = user_cart.get_cart_info()['order']
    order_products = order.orderproduct_set.all()
    for order_product in order_products:
        quantity = order_product.quantity

store/templates/store/components/FAQs.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
 {{ title }}
{% endblock title %}
{% block main %}


<style>
    .main-content {
    padding-top: 100px;
    padding-bottom: 100px;
}

.flex-center {
    align-items: center;
}
.accordion-button{
    margin-bottom: 10px;
}
.accordion-body {
    margin-top: 15px;
    padding: 25px;
    background: #fff;
    border-radius: 5px;
    box-shadow: 0 2px 25px -3px rgba(0, 0, 0, 0.1);
    margin-bottom: 10px;
}

.circle-icon {
    height: 50px;
    width: 50px;
    border-radius: 50px;
    display: flex;
    justify-content: center;
    align-items: center;
    background: #2b4eff;
    border: 5px solid #b2bfff;
    color: #fff;
    margin-left: -20px;
    margin-right: 10px;
    transform: scale(1.2);
}
.accordion-item{
    border: 0px!important;
}
.accordion-button:not(.collapsed){
    border: 0px!important;
    color: #0c63e4;
    background-color: #ffffff;
    box-shadow: inset 0 0px 0 rgb(0 0 0 / 13%);
}


</style>
<main>
<section class="main-content">
  <div class="container">
    <h1 class="text-center text-uppercase mb-5">Frequently Asked Questions</h1>
    <br>
    <br>
    <div class="row flex-center">
      <div class="col-sm-10 offset-sm-2">
        <div class="accordion" id="accordionExample">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              <div class="circle-icon"> <i class="fa fa-question"></i> </div>
              <span>How to Create FAQ Section</span> </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
              <div class="accordion-body"> <strong>This is the first item's accordion body.</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                <div class="circle-icon"> <i class="fa fa-question"></i> </div>
              <span>What jQuery do I need?</span> </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
              <div class="accordion-body"> <strong>This is the second item's accordion body.</strong> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingThree">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                <div class="circle-icon"> <i class="fa fa-question"></i> </div>

              <span>HTML CSS FAQ Design With jQuery Accordion</span> </button>

            </h2>
            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
              <div class="accordion-body"> <strong>This is the third item's accordion body.</strong> At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis  </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

</main>
{% endblock main %}

store/templates/store/components/_carousel.html
{% load static %}
<div class="container-fluid mb-3">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <div id="header-carousel" class="carousel slide carousel-fade mb-30 mb-lg-0" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#header-carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#header-carousel" data-slide-to="1"></li>
                        <li data-target="#header-carousel" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item position-relative active" style="height: 430px;">
                            <img class="position-absolute w-100 h-100" src="{% static 'store/img/carousel-1.jpg' %}" style="object-fit: cover;">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Men Fashion</h1>
                                    <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                    <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">Shop Now</a>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item position-relative" style="height: 430px;">
                            <img class="position-absolute w-100 h-100" src="{% static 'store/img/carousel-2.jpg' %}" style="object-fit: cover;">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Women Fashion</h1>
                                    <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                    <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">Shop Now</a>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item position-relative" style="height: 430px;">
                            <img class="position-absolute w-100 h-100" src="{% static 'store/img/carousel-3.jpg' %}" style="object-fit: cover;">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Kids Fashion</h1>
                                    <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                    <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">Shop Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="product-offer mb-30" style="height: 200px;">
                    <img class="img-fluid" src="{% static 'store/img/offer-1.jpg' %}" alt="">
                    <div class="offer-text">
                        <h6 class="text-white text-uppercase">Save 20%</h6>
                        <h3 class="text-white mb-3">Special Offer</h3>
                        <a href="" class="btn btn-primary">Shop Now</a>
                    </div>
                </div>
                <div class="product-offer mb-30" style="height: 200px;">
                    <img class="img-fluid" src="{% static 'store/img/offer-2.jpg' %}" alt="">
                    <div class="offer-text">
                        <h6 class="text-white text-uppercase">Save 20%</h6>
                        <h3 class="text-white mb-3">Special Offer</h3>
                        <a href="" class="btn btn-primary">Shop Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

store/templates/store/components/_cart_row.html
{% load static %}
<div class="cart-row">
<div style="flex:2"><img class="row-image" src="{{  item.product.get_first_photo}}"></div>
    <div style="flex:2"><p>{{ item.product.title }}</p></div>
    <div style="flex:1"><p>${{ item.product.price }}</p></div>
    <div style="flex:1"><p class="quantity">{{ item.quantity }}</p>
      {% if 'cart' in request.path %}
        <div class="quantity">
            {% if item.product.quantity > 0 %}
            <a href="{% url 'store:to_cart' item.product.pk 'add' %}">
             <img data-product="id" data-actions="add"
                     class="chg-quantity update-cart"
                     src="{% static 'store/images/arrow-up.png' %}">
            </a>
            {% endif %}
            <a href="{% url 'store:to_cart' item.product.pk 'delete' %}">
                <img data-product="id" data-actions="remove"
                     class="chg-quantity update-cart"
                     src="{% static 'store/images/arrow-down.png' %}">
            </a>
        </div>
        {% endif %}

    </div>

    <div style="flex:1">${{ item.get_total_price }}</div>
</div>

store/templates/store/components/_vendor.html
{% load static %}
 <div class="container-fluid py-5 bg-light">
        <div class="row px-xl-5">
            <div class="col">
                <div class="owl-carousel vendor-carousel ">
                    <div class="bg-light p-4">
                        <img src="{% static 'store/img/vendor-1.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'store/img/vendor-2.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'store/img/vendor-3.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'store/img/vendor-4.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'store/img/vendor-5.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'store/img/vendor-6.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'store/img/vendor-7.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'store/img/vendor-8.jpg' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>

store/templates/store/components/logout.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
 {{ title }}
{% endblock title %}
{% block main %}



<div class="home-center">
<div class="home-desc-center">
<div class="container">
<div class="row justify-content-center">
<div class="col-lg-4 col-md-6">
<div class="login-page bg-white shadow rounded p-4">
<div class="text-center">
<h4 class="mb-4">You have been logged out</h4>
<br>
<div class="row">
<div class="col-md-6">
<a href="{% url 'store:login' %}"><button class="btn btn-primary w-100">Login</button></a>
</div>
<div class="col-md-6">
<a href="{% url 'home_page' %}"><button class="btn btn-info w-100">Home</button></a>
</div>
</div>
</div>
</div> <!--end col-->
</div><!--end row-->
</div> <!--end container-->
</div>
</div>
</div>
{% endblock main %}

store/templates/store/components/offer.html
{% load static %}
<div class="container-fluid pt-5 pb-3">
        <div class="row px-xl-5">
            <div class="col-md-6">
                <div class="product-offer mb-30" style="height: 300px;">
                    <img class="img-fluid" src="{% static 'store/img/offer-1.jpg' %}" alt="">
                    <div class="offer-text">
                        <h6 class="text-white text-uppercase">Save 20%</h6>
                        <h3 class="text-white mb-3">Special Offer</h3>
                        <a href="" class="btn btn-primary">Shop Now</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="product-offer mb-30" style="height: 300px;">
                    <img class="img-fluid" src="{% static 'store/img/offer-2.jpg' %}" alt="">
                    <div class="offer-text">
                        <h6 class="text-white text-uppercase">Save 20%</h6>
                        <h3 class="text-white mb-3">Special Offer</h3>
                        <a href="" class="btn btn-primary">Shop Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>