multishop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _



urlpatterns = [
    path(r'^currencies/', include('currencies.urls')),
    path(_('admin/'), admin.site.urls),
    #  path('', include('store.urls')),
]

urlpatterns += i18n_patterns(
    path('i18n', include('django.conf.urls.i18n')),
    path('', include('store.urls', namespace='store')),
   # path('selectcurrency/', selectcurrency, name='selectcurrency'),
   # path('savelangcurr/', savelangcurr, name='savelangcurr'),
    prefix_default_language=False
)
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *

app_name = 'store'

urlpatterns = [
    # path('', ProductListView.as_view, name='product_list'),
    path('', product_list, name='product_list'),
    path('category/<int:category_id>/', category_products, name='category'),
    #  path('product/<slug:slug>/', product_detail, name='product_detail'),
    path('category/<slug:slug>/', category_page, name='category_detail'),
    path('product/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    # path('request/', RequestInfoView.as_view(), name='request'),
    path('cart/', cart, name='cart'),
    path('to_cart/<int:product_id>/<str:action>/', to_cart, name='to_cart'),
    path('clear_cart/', clear_cart, name='clear_cart'),
    path('checkout/', checkout, name='checkout'),
    path('shop/', shop, name='shop'),
    path('payment/', create_checkout_sessions, name='payment'),
    path('payment_success/', successPayment, name='success'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('contact/', contact, name='contact'),
    path('shop_detail/', shop_detail, name='shop_detail'),
    path('about/', about, name='about'),
    path('FAQ/', FAQs, name='FAQs'),
    path('profile/', profile, name='users-profile'),
    path('selectcurrency/', selectcurrency, name='selectcurrency'),
    path('savelangcurr/', savelangcurr, name='savelangcurr'),
]

store/forms.py
from django import forms
import datetime
import re
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.translation import gettext_lazy as _
from django.utils.translation import activate, get_language


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control',
                                                 'placeholder': 'Firstname...'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control',
                                                'placeholder': 'Lastname...'})
        }


class ShippingForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = ['address', 'city', 'state', 'shipping_zip', 'phone']
        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control',
                                              'placeholder': 'Address...'}),
            'city': forms.Select(attrs={'class': 'form-select',
                                        'placeholder': 'City...'}),
            'state': forms.TextInput(attrs={'class': 'form-control',
                                            'placeholder': 'State...'}),
            'shipping_zip': forms.TextInput(attrs={'class': 'form-control',
                                                   'placeholder': 'Shipping Zip...'}),
            'phone': forms.TextInput(attrs={'class': 'form-control',
                                            'placeholder': 'Phone...'})
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Username:', max_length=16, help_text="Max 16 symbols",
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Username'
                               }))
    password = forms.CharField(label='Password:', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Your Password'
    }))


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your Password'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Submit Password'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username'
    }))
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Your name'
        }))
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Your surname'
        }))
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Your email address'
        }))
    birthday = forms.DateTimeField(widget=forms.DateTimeInput(attrs={
        'class': 'form-control',
        'placeholder': 'Birthday'
    }))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'birthday', 'password1', 'password2')

    check = forms.BooleanField(required=True)


def cc_expire_years():
    current_year = datetime.datetime.now().year
    years = range(current_year, current_year + 12)
    return [(str(x), str(x)) for x in years]


def cc_expire_months():
    months = []
    for month in range(1, 13):
        if len(str(month)) == 1:
            numeric = '0' + str(month)
        else:
            numeric = str(month)

        months.append((numeric, datetime.date(2021, 3, 2).strftime('%B')))

    return months


CARD_TYPES = (('Mastercard', 'Mastercard'),
              ('VISA', 'VISA'),
              ('AMEX', 'AMEX'),
              ('Discover', 'Discover'),)


def strip_non_numbers(data):
    """ gets rid of all non-number characters """
    non_numbers = re.compile('\D')
    return non_numbers.sub('', data)


# Gateway test credit cards won't pass this validation
def cardLuhnChecksumIsValid(card_number):
    """ checks to make sure that the card passes a luhn mod-10 checksum """
    sum = 0
    num_digits = len(card_number)
    oddeven = num_digits & 1
    for count in range(0, num_digits):
        digit = int(card_number[count])
        if not ((count & 1) ^ oddeven):
            digit = digit * 2
        if digit > 9:
            digit = digit - 9
        sum = sum + digit
    return ((sum % 10) == 0)

store/views.py
from django.core.checks import messages
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.utils import translation

from .models import *
from django.views.generic import DetailView, ListView, CreateView
from random import randint
from .forms import CustomerForm, ShippingForm
from .utils import *

import stripe
from django.contrib import messages
from .forms import RegisterForm, LoginForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _
from django.utils.translation import activate, get_language, gettext
from multishop import settings


# Create your views here.
# class ProductListView(ListView):
#  model = Product
#  context_object_name = 'categories'

# extra_context = {
#     'title': 'MULTI SHOP - ONLINE',

#  }
# template_name = 'store/product_list.html'

#  def get_queryset(self):
#    categories = Category.objects.filter(parent=None)
#   return categories


def profile(request):
    return render(request, 'users/profile.html')


def product_list(request):
    if not request.session.has_key('currency'):
        request.session['currency'] = settings.DEFAULT_CURRENCY

    #  setting = Setting.objects.get(pk=1)
    products = Product.objects.all().order_by('-id')[:4]
    defaultlang = settings.LANGUAGE_CODE[0:2]
    currentlang = request.LANGUAGE_CODE[0:2]

    if defaultlang != currentlang:
        setting = settings.LANGUAGES.objects.get(language=currentlang)
        products = Product.objects.row(
            'SELECT p.id, p.price, l.title, l.description, l.slang'
            'FROM product as p'
            'LEFT JOIN productlang as l '
            'ON p.id = l.product_id'
            'WHERE l.language ORDER_BY p.id DESC LIMIT 4', [currentlang]
        )

    products_slider = Product.objects.all().order_by('id')[:4]
    products_picked = Product.objects.all().order_by('?')[:4]
    categories = Category.objects.filter(parent=None)
    trans = translate(language='ru')
    context = {
        'title': 'MULTI SHOP - ONLINE',
        'setting': 'setting',
        'categories': categories,
        'products': products,
        'products_slider': products_slider,
        'products_picked': products_picked,
        'trans': trans,

    }
    return render(request, 'store/product_list.html', context)


def translate(language):
    cur_language = get_language()
    try:
        activate(language)
        text = gettext('Shopping')
    finally:
        activate(cur_language)
    return text


def category_products(request, category_id, category_slug):
    products = Product.objects.filter(category_id=category_id)
    products = products.order_by('-created_at')

    category = Category.objects.get(pk=category_id, slug=category_slug)
    categories = Category.objects.all()
    if category_slug:
        category_slug = get_object_or_404(Category, slug=category_slug)
    context = {
        'title': f'Category: {category.title}',
        'categories': categories,
        'products': products,
        'category': category_slug
    }

    return render(request, 'components/_nav.html', context)


# def product_detail(request, slug):
#  product = get_object_or_404(Product, slug=slug, quantity=True)
# product = Product.objects.get(slug=slug)
# context = {
#     'product': product
# }
# return render(request, 'store/components/product_detail.html', context)
# class RequestInfoView(CreateView):
#  template_name = 'request_info.html'
# form_class = RequestInfoForm
# success_url = '/thanks/'

#  def form_valid(self, form):
#     name = form.cleaned_data['name']
#    email = form.cleaned_data['email']
#   phone = form.cleaned_data['phone']
#  state = form.cleaned_data['state']
# vendor = form.cleaned_data['vendor']
# product_name = form.cleaned_data['product']

# message = name + " " + email + " " + state + " " + str(product_name)

#  html_message = render_to_string('mail_request.html', context=({'name': name,
#                                                                'email': email,
#                                                              'phone': phone,
#                                                             'state': state,
#                                                              'product': product_name}))
# try:
#    send_mail('Sales Inquiry from: ' + name, message, email, ['test@example.com'],
#             html_message=html_message)
# except:
#   return HttpResponse('Invalid header found.')
# return super().form_valid(form)


class ProductDetail(DetailView):
    model = Product
    template_name = 'store/components/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        product = Product.objects.get(slug=self.kwargs['slug'])
        context['title'] = f'Product: {product.title}'

        products = Product.objects.all()
        data = []
        for i in range(0):
            random_index = randint(0, len(products))
            p = products[random_index]

            if p not in data:
                data.append(p)

        context['products'] = data

        return context


# class CategoryView(ListView):
#    model = Product
#    context_object_name = 'products'
#  template_name = 'store/_category_page.html'

#   def get_queryset(self):
#      main_category = Category.objects.get(slug=self.kwargs['slug'])
#     subcategories = main_category.subcategories.all()
#    data = []
#     for subcategory in subcategories:
#        products = subcategory.products.all()
#        for product in products:
#            data.append(product)
#           return data


def category_page(request, slug):
    main_category = Category.objects.get(category=request.POST.get('category'), slug=slug)
    subcategories = main_category.subcategories.all()
    products = Product.objects.filter(category__in=subcategories)
    paginate_by = 4

    context = {
        'products': products,
        'main_category': main_category,
        'subcategories': subcategories,
        'pagination': paginate_by
    }

    sort_fields = request.Get.get('sort')
    if sort_fields:
        context['products'] = context['products'].order_by(*sort_fields)

    return render(request, 'store/category_page.html', context)


def cart(request):
    cart_info = get_cart_data(request)

    context = {
        'cart_total_quantity': cart_info['cart_total_quantity'],
        'order': cart_info['order'],
        'products': cart_info['products']
    }
    return render(request, 'store/cart.html', context)


def to_cart(request, product_id, action):
    if request.user.is_authenticated:
        user_cart = CartForAuthenticatedUser(request, product_id, action)
        return redirect('cart', {'user_cart': user_cart})
    else:
        messages.error(request, "Xaridni amalga oshirish uchun, Avrotizatsiyadan yoki ro'yxatdan o'ting")
        return redirect('login_registration')


def checkout(request):
    cart_info = get_cart_data(request)
    context = {
        'cart_total_quantity': cart_info['cart_total_quantity'],
        'order': cart_info['order'],
        'items': cart_info['products'],
        'customer_form': CustomerForm(),
        'shipping_form': ShippingForm(),
        'title': 'Make an order'
    }
    return render(request, 'store/checkout.html', context)


def shop(request):
    return render(request, 'store/shop.html', {})


def create_checkout_sessions(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    if request.method == 'POST':
        '''Bu yerda foydalanuvchi ma'lumotlarini saqlaymiz.'''
        user_cart = CartForAuthenticatedUser(request)
        cart_info = user_cart.get_cart_info()
        customer_form = CustomerForm(data=request.POST)
        if customer_form.is_valid():
            customer = Customer.objects.get(user=request.user)
            customer.first_name = customer_form.cleaned_data['first_name']
            customer.last_name = customer_form.cleaned_data['last_name']
            customer.save()
            user = User.objects.get(username=request.user.username)
            user.first_name = customer_form.cleaned_data['first_name']
            user.last_name = customer_form.cleaned_data['last_name']
            user.save()
        shipping_form = ShippingForm(data=request.POST)
        if shipping_form.is_valid():
            address = shipping_form.save(commit=False)
            address.customer = Customer.objects.get(user=request.user)
            address.order = user_cart.get_cart_info()['order']
            address.save()

        total_price = cart_info['cart_total_price']
        total_quantity = cart_info['cart_total_quantity']
        session = stripe.checkout.Session.create(
            line_items=[{
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': 'Products'
                    },
                    'unit_amount': int(total_price * 100)
                },
                'quantity': total_quantity
            }],
            mode='payment',
            success_url=request.build_absolute_uri(reverse('success')),
            cancel_url=request.build_absolute_uri(reverse('success')),
        )
        return redirect(session.url, 303)


def successPayment(request):
    user_cart = CartForAuthenticatedUser(request)
    user_cart.clear()
    messages.success(request, "The Payment was made successfully!")
    return render(request, 'store/success.html')


def clear_cart(request):
    user_cart = CartForAuthenticatedUser(request)
    order = user_cart.get_cart_info()['order']
    order_products = order.orderproduct_set.all()
    for order_product in order_products:
        quantity = order_product.quantity

store/templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
 {{ title }}
{% endblock title %}
{% block main %}

<main>
  <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th><h5>Products: <strong>{{ order.get_cart_total_quantity }}</strong></h5></th>
                            <th><h5>Price: <strong>{{ order.get_cart_total_price }}</strong></h5> </th>
                            <th>Quantity:{{ item.get_total_quantity }}</th>
                            <th>Total:${{ item.get_total_price }}</th>
                            <th><a class="btn btn-danger" href="{% url 'store:clear_cart' %}">Clean cart</a></th>
                        </tr>
                    </thead>
                    {% for item in products %}
{% include 'store/components/_cart_row.html' %}
{% endfor %}
                    <tbody class="align-middle">
                        <tr>
                            <td class="align-middle"><img src="img/product-1.jpg" alt="" style="width: 50px;"> Product Name</td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-minus" >
                                        <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="1">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
                        </tr>
                        <tr>
                            <td class="align-middle"><img src="img/product-2.jpg" alt="" style="width: 50px;"> Product Name</td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-minus" >
                                        <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="1">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
                        </tr>
                        <tr>
                            <td class="align-middle"><img src="img/product-3.jpg" alt="" style="width: 50px;"> Product Name</td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-minus" >
                                        <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="1">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
                        </tr>
                        <tr>
                            <td class="align-middle"><img src="img/product-4.jpg" alt="" style="width: 50px;"> Product Name</td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-minus" >
                                        <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="1">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
                        </tr>
                        <tr>
                            <td class="align-middle"><img src="img/product-5.jpg" alt="" style="width: 50px;"> Product Name</td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-minus" >
                                        <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="1">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">$150</td>
                            <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>$150</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">$10</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>$160</h5>
                        </div>
                        <a class="btn btn-primary" href="{% url 'store:clear_cart' %}">Clear cart</a>
                       <a class="btn btn-primary" href="{% url 'store:product_list' %}">Proceed to buy</a>
                        <a href="{% url 'store:checkout' %}">
                        <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Checkout</button>
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->

</main>
{% endblock main %}

store/templates/store/product_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
 {{ title }}
{% endblock title %}
{% block main %}
 <!-- Carousel Start -->
  {% include 'store/components/_carousel.html' %}
    <!-- Carousel End -->


    <!-- Featured Start -->
  {% include 'store/components/_shipping.html' %}
    <!-- Featured End -->


  {% include 'store/components/_categories.html' %}
    <!-- Categories End -->


    <!-- Products Start -->

    {% include 'store/components/_products.html' %}

    <!-- Products End -->


    <!-- Offer Start -->
   {% include 'store/components/offer.html' %}
    <!-- Offer End -->


    <!-- Recent products Start -->
   {% include 'store/components/_recent_products.html' %}
    <!-- Recent products End -->



    <!-- Vendor Start -->
   {% include 'store/components/_vendor.html' %}
    <!-- Vendor End -->


{% endblock main %}

store/templates/store/success.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock title %}

{% block main %}
<div class="container">
    <div class="content">
        <h2>The payment was made successfully!</h2>
        <p>You may proceed to buy</p>
        <a href="{% url 'store:product_list' %}" class="btn btn-success">Back to Home</a>
    </div>
</div>
{% endblock main %}