multishop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _



urlpatterns = [
    path(r'^currencies/', include('currencies.urls')),
    path(_('admin/'), admin.site.urls),
    #  path('', include('store.urls')),
]

urlpatterns += i18n_patterns(
    path('i18n', include('django.conf.urls.i18n')),
    path('', include('store.urls', namespace='store')),
   # path('selectcurrency/', selectcurrency, name='selectcurrency'),
   # path('savelangcurr/', savelangcurr, name='savelangcurr'),
    prefix_default_language=False
)
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *

app_name = 'store'

urlpatterns = [
    # path('', ProductListView.as_view, name='product_list'),
    path('', product_list, name='product_list'),
    path('category/<int:category_id>/', category_products, name='category'),
    #  path('product/<slug:slug>/', product_detail, name='product_detail'),
    path('category/<slug:slug>/', category_page, name='category_detail'),
    path('product/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    # path('request/', RequestInfoView.as_view(), name='request'),
    path('cart/', cart, name='cart'),
    path('to_cart/<int:product_id>/<str:action>/', to_cart, name='to_cart'),
    path('clear_cart/', clear_cart, name='clear_cart'),
    path('checkout/', checkout, name='checkout'),
    path('shop/', shop, name='shop'),
    path('payment/', create_checkout_sessions, name='payment'),
    path('payment_success/', successPayment, name='success'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('contact/', contact, name='contact'),
    path('shop_detail/', shop_detail, name='shop_detail'),
    path('about/', about, name='about'),
    path('FAQ/', FAQs, name='FAQs'),
    path('profile/', profile, name='users-profile'),
    path('selectcurrency/', selectcurrency, name='selectcurrency'),
    path('savelangcurr/', savelangcurr, name='savelangcurr'),
]

templates/components/_footer.html
{% load static %}
<div class="container-fluid bg-dark text-secondary mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
                <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor. Rebum tempor no vero est magna amet no</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                        <p>Duo stet tempor ipsum sit amet magna ipsum tempor est</p>
                        <form action="">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Your Email Address">
                                <div class="input-group-append">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </div>
                        </form>
                        <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                        <div class="d-flex">
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-secondary">
                    &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                    by
                    <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="{% static 'store/img/payments.png' %}" alt="">
            </div>
        </div>
    </div>

templates/components/_nav.html
{% load i18n %}
{% load store_tags %}
<div class="container-fluid bg-dark mb-30">
        <div class="row px-xl-5">

            <div class="col-lg-3 d-none d-lg-block">


                <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                    <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categories</h6>
                    <i class="fa fa-angle-down text-dark"></i></a>

                {% get_categories as categories %}
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-dark" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">

                    <ul class="category-list ">

                        <li class="dropdown side-dropdown">

                            <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="true" >{{ category.title }}<i class="fa fa-angle-right float-right mt-1"></i></a>

                            <div class="dropdown-menu bg-dark">

                              <div class="row">
                                  <div class="col-md-4">

    {% for subcategory in category.subcategories.all %}
                                 <ul class="children">

                                     <h6 class="list-links-title text-light text-center">{{subcategory.title}}</h6>

                                     <li><a href=""></a></li>



                                 </ul>
       {% endfor %}

                                      <hr class="hidden-md hidden-lg">
                                  </div>
                              </div>

                            </div>

                        </li>

                    </ul>

                </nav>

            </div>

            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                    <a href="{% url 'store:product_list' %}" class="text-decoration-none d-block d-lg-none">
                        <span class="h1 text-uppercase text-dark bg-light px-2">Multi</span>
                        <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="{% url 'store:product_list' %}" class="nav-item nav-link active">Home</a>
                            <a href="{% url 'store:shop' %}" class="nav-item nav-link">Shop</a>
                            <a href="{% url 'store:shop_detail' %}" class="nav-item nav-link">Shop Detail</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{ trans }}<i class="fa fa-angle-down mt-1"></i></a>
                                <div class="dropdown-menu bg-primary rounded-0 border-0 m-0">
                                    <a href="{%url 'store:cart' %}" class="dropdown-item">Shopping Cart</a>
                                    <a href="{% url 'store:checkout' %}" class="dropdown-item">Checkout</a>
                                </div>
                            </div>
                            <a href="{% url 'store:contact' %}" class="nav-item nav-link">Contact</a>
                        </div>
                         <!-- Sorters -->
 {% include 'store/components/sort.html' %}
<!-- End Sorters -->
    <!-- Categories Start -->
                        <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                            <a href="" class="btn px-0">
                                <i class="fas fa-heart text-primary"></i>
                                <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">0</span>
                            </a>
                            <a href="" class="btn px-0 ml-3">
                                <i class="fas fa-shopping-cart text-primary"></i>
                                <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">0</span>
                            </a>
                       </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>

templates/components/_scripts.html
{% load static %}
 <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'store/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'store/lib/owlcarousel/owl.carousel.min.js' %}"></script>
     <script src="{% static 'store/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <!-- Contact Javascript File -->
    <script src="{% static 'store/mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'store/mail/contact.js' %}"></script>
    <script src="{% static 'store/bootsrap/js/bootsrap.bundle.min.js' %}"></script>
    <!-- Template Javascript -->
    <script src="{% static 'store/js/main.js' %}"></script>

templates/components/_styles.html
{% load static %}
 <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">
  <link rel="preconnect" href="https://fonts.gstatic.com">
 <!-- Google Web Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'store/lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'store/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'store/bootsrap/css' %}">
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'store/css/style.css' %}" rel="stylesheet">

templates/components/_topbar.html
 {% load i18n %}
 {% load currency %}
<div class="container-fluid">
        <div class="row bg-secondary py-1 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center h-100">
                    <a class="text-body mr-3" href="{% url 'store:about' %}">{% trans 'About' %}</a>
                    <a class="text-body mr-3" href="{% url 'store:contact' %}">Contact</a>
                    <a class="text-body mr-3" href="">Help</a>
                    <a class="text-body mr-3" href="{% url 'store:FAQs' %}">FAQs</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">My Account</button>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a href="{% url 'store:login' %}">
                            <button class="dropdown-item" type="button">Sign in</button>
                            </a>
                            <a href="{% url 'store:register' %}">
                            <button class="dropdown-item" type="button">Sign up</button>
                            </a>
                        </div>
                    </div>
                    <div class="btn-group mx-2">
                        <form action="{% url 'store:selectcurrency' %}" method="post" id="currency_switcher">
                            {% csrf_token %}
                            <select name="currency" id="#" onchange="submit()">
                        {% for curr in CURRENCIES %}
                                <option value="{{ curr.code }}">
                                    {% if curr.code == request.session.currency %}{% endif %}
                                    {{ curr.symbol }} {{ curr.name }}

                                </option>
                                {% endfor %}
                            </select>
                                <input type="submit" value="Set">

                        </form>
                        </div>

                    <div class="btn-group">
                        <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                            <input type="hidden" name="next" value="{{ redirect_to }}">
                            <select name="language" id="">
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                                    {{ language.name_local }} ({{ language.code }})
                                </option>
                                {% endfor %}
                            </select>
                            <input type="submit" value="Go">
                        </form>
                        </div>
                    </div>
                </div>
                <div class="d-inline-flex align-items-center d-block d-lg-none">
                    <a href="" class="btn px-0 ml-2">
                        <i class="fas fa-heart text-dark"></i>
                        <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                    </a>
                    <a href="" class="btn px-0 ml-2">
                        <i class="fas fa-shopping-cart text-dark"></i>
                        <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
            <div class="col-lg-4">
                <a href="{% url 'store:product_list' %}" class="text-decoration-none">
                    <span class="h1 text-uppercase text-primary bg-dark px-2">Multi</span>
                    <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
                </a>
            </div>
            <div class="col-lg-4 col-6 text-left">
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for products">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 col-6 text-right">
                <p class="m-0">Customer Service</p>
                <h5 class="m-0">+012 345 6789</h5>
            </div>
        </div>
    </div>
    <!-- Topbar End -->